### ISSUE TITLE
Transform logic & History table (AccountTransactions)

### ISSUE THREAD

**Issue by robcxyz** [geometry-labs/icon-accounts#2]
The transform logic needs to operate as follows. 

- Check if the transaction is **to** a unique address.
  - SQL: `select * from accounts where address = XX`  
- If the address does not exist, insert a new record into the table 
  - Will set transaction_count to 1, get balance with RPC call (below)
- If the address does exist
  - Check if the transaction is newer than the last updated date
    - If it is, get the balance with an RPC call
  - Update the record with the new balance (if applicable) and increment the transaction count 

### Getting the balance of an address JSON RPC 

- https://github.com/icon-project/icon-rpc-server/blob/master/docs/icon-json-rpc-v3.md#icx_getbalance

- Balance will be stored as hex 

- POST to https://icon.geometry-dev.net/api/v3
```
{
    "jsonrpc": "2.0",
    "method": "icx_getBalance",
    "id": 1234,
    "params": {
        "address": "hxb0776ee37f5b45bfaea8cff1d8232fbb6122ec32" 
    }
}
```

Schemas in #1

**Comment by anuragjha** [comment]
Add a Running balance column
